const actions = {
  PROMPT_BOX_CONTROL: 'PROMPT_BOX_CONTROL',
  FRIENDS_NAVIGATOR_BOX_CONTROL: 'FRIENDS_NAVIGATOR_BOX_CONTROL',
  FRIENDS_LIST: 'FRIENDS_LIST',
  THEME_SELECTOR_BOX_CONTROL: 'THEME_SELECTOR_BOX_CONTROL',
  ACCOUNT_BOX_CONTROL: 'ACCOUNT_BOX_CONTROL',
  APP_INFO_BOX_CONTROL: 'APP_INFO_BOX_CONTROL',
  ACCOUNT_EDIT_MODE: 'ACCOUNT_EDIT_MODE',
  ACCOUNT_DELETE_MODE: 'ACCOUNT_DELETE_MODE',
  USER_AUTH: 'USER_AUTH',
  USER_DATA: 'USER_DATA',
  CHAT_DATA: 'CHAT_DATA',
  CHAT_LIST_DATA: 'CHAT_LIST_DATA',
  IS_CONNECTED: 'IS_CONNECTED',
};

export default actions;
