const actions = {
  PROMPT_BOX_CONTROL: 'PROMPT_BOX_CONTROL',
  THEME_SELECTOR_BOX_CONTROL: 'THEME_SELECTOR_BOX_CONTROL',
  ACCOUNT_BOX_CONTROL: 'ACCOUNT_BOX_CONTROL',
  APP_INFO_BOX_CONTROL: 'APP_INFO_BOX_CONTROL',
  ACCOUNT_EDIT_MODE: 'ACCOUNT_EDIT_MODE',
  USER_AUTH: 'USER_AUTH',
  USER_DATA: 'USER_DATA',
};

export default actions;
